[service]
name = "poe-mcp-server"

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python poe_server_phase2.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100
region = "us-west1"
